# Update Time: 2023-09-02 21:00
version: "3.4"

services:
  # Drpy
  drpy:
    image: esme518/docker-drpy
    networks: [network_cluster]
    restart: on-failure
    # ports:
    #   - 5705:5705
    #   - 9001:9001
    environment:
      user: root
      # INET_USERNAME: ${DRPY_USERNAME}
      # INET_PASSWORD: ${DRPY_PASSWORD}
      TZ: ${TZ}       
    volumes:
      - nfs_drpy:/root/sd/pywork/dr_py
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drpy.rule=Host(`drpy.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpy.entrypoints=websecure"
        - "traefik.http.routers.drpy.service=drpy"
        - "traefik.http.routers.drpy.middlewares=noauth-chain@file"
        - "traefik.http.services.drpy.loadbalancer.server.port=5705"
        - "traefik.http.routers.drpys.rule=Host(`drpys.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpys.entrypoints=websecure"
        - "traefik.http.routers.drpys.service=drpys"
        - "traefik.http.routers.drpys.middlewares=noauth-chain@file"
        - "traefik.http.services.drpys.loadbalancer.server.port=9001"
        - homepage.group=Media
        - homepage.name=Drpy
        - homepage.icon=kamatera.png
        - homepage.href=https://drpy.${DOMAIN_SWARM}:4/admin/
        - homepage.description=影音源管理       
        - homepage.siteMonitor=http://drpy:5705        
        - homepage.weight=10          
      mode: replicated
      replicas: 2
      placement:
        constraints:
          # - node.labels.type == vm
          - node.labels.type == nas
          - node.labels.media == true
          # - node.labels.nas == primary          

  # Drpy(自动更新)
  drpy2:
    image: esme518/docker-drpy
    networks: [network_cluster]
    restart: on-failure
    environment:
      user: root
      # INET_USERNAME: ${DRPY_USERNAME}
      # INET_PASSWORD: ${DRPY_PASSWORD}
      TZ: ${TZ}     
    volumes:
      - nfs_drpy2:/root/sd/pywork/dr_py
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drpy2.rule=Host(`drpy2.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpy2.entrypoints=websecure"
        - "traefik.http.routers.drpy2.service=drpy2"
        - "traefik.http.routers.drpy2.middlewares=noauth-chain@file"
        - "traefik.http.services.drpy2.loadbalancer.server.port=5705"
        - "traefik.http.routers.drpys2.rule=Host(`drpys2.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpys2.entrypoints=websecure"
        - "traefik.http.routers.drpys2.service=drpys2"
        - "traefik.http.routers.drpys2.middlewares=noauth-chain@file"
        - "traefik.http.services.drpys2.loadbalancer.server.port=9001"
        - homepage.group=Media
        - homepage.name=Drpy2
        - homepage.icon=kamatera.png
        - homepage.href=https://drpy2.${DOMAIN_SWARM}:4/admin/
        - homepage.description=影音源管理(自动更新)
        - homepage.siteMonitor=http://drpy2:5705        
        - homepage.weight=10          
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          # - node.labels.type == nas
          - node.labels.media == true
          # - node.labels.nas == primary                          

  # TVBox
  tvbox:
    image: haroldli/xiaoya-tvbox:latest
    networks: [network_cluster]
    restart: on-failure
    # ports:
    #   - 4567:4567
    #   - 5244:80
    environment:
      ALIST_PORT: 5244
      TZ: ${TZ}       
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.tvbox.rule=Host(`tvbox.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.tvbox.entrypoints=websecure"
        - "traefik.http.routers.tvbox.service=tvbox"
        - "traefik.http.routers.tvbox.middlewares=noauth-chain@file"
        - "traefik.http.services.tvbox.loadbalancer.server.port=4567"
        - "traefik.http.routers.tvbox2.rule=Host(`tvbox2.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.tvbox2.entrypoints=websecure"
        - "traefik.http.routers.tvbox2.service=tvbox2"
        - "traefik.http.routers.tvbox2.middlewares=noauth-chain@file"
        - "traefik.http.services.tvbox2.loadbalancer.server.port=5244"
        - homepage.group=Media
        - homepage.name=TVBox
        - homepage.icon=truenas.png
        - homepage.href=https://tvbox.${DOMAIN_SWARM}:4
        - homepage.description=影音源管理(另一方案)
        - homepage.siteMonitor=http://tvbox:4567
        - homepage.weight=10          
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true    

  # MyAlist
  myalist:
    image: xhofe/alist:latest
    networks: [network_cluster]
    restart: on-failure
    environment:
      PUID: ${MYALIST_PUID}
      PGID: ${MYALIST_PGID}
      UMASK: ${MYALIST_UMASK}
      TZ: ${TZ}       
    volumes:
      - nfs_mylist:/opt/alist/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myalist.rule=Host(`myalist.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.myalist.entrypoints=websecure"
        - "traefik.http.routers.myalist.middlewares=noauth-chain@file"
        - "traefik.http.services.myalist.loadbalancer.server.port=5244"
        - homepage.group=Media
        - homepage.name=Alist
        - homepage.icon=https://www.waylon.wang:4/images/services/alist.png
        - homepage.href=https://myalist.${DOMAIN_SWARM}:4/
        - homepage.description=多媒体列表       
        - homepage.siteMonitor=http://myalist:5244        
        - homepage.weight=20         
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true

  # NAS-Tools
  # nastool:
  #   image: shmilyin/nas-tools:2.9.1
  #   networks: [network_cluster]
  #   restart: on-failure  
  #   extra_hosts:
  #     - "api.themoviedb.org:65.9.17.17"    
  #   environment:
  #     # 直接使用Portainer容器内的环境变量
  #     PUID: ${MEDIA_PUID}
  #     PGID: ${MEDIA_PGID}
  #     UMASK: ${MEDIA_UMASK}
  #     NASTOOL_AUTO_UPDATE: ${NASTOOL_AUTO_UPDATE}
  #     NASTOOL_CN_UPDATE: ${NASTOOL_CN_UPDATE}
  #     TZ: ${TZ}
  #   volumes:
  #     - nfs_nastool_media:/media
  #     - nfs_nastool_media_ext:/media_ext
  #     - nfs_nastool_config:/config
  #     - nfs_nastool_src:/nas-tools
  #   ports:
  #     - 3000:3000
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.http.routers.nastool.rule=Host(`nastool.${DOMAIN_SWARM}`)"
  #       - "traefik.http.routers.nastool.entrypoints=websecure"
  #       - "traefik.http.routers.nastool.service=nastool"
  #       - "traefik.http.routers.nastool.middlewares=noauth-chain@file"
  #       - "traefik.http.services.nastool.loadbalancer.server.port=3000"      
  #       - homepage.group=Media
  #       - homepage.name=NASTool
  #       - homepage.icon=https://www.waylon.wang:4/images/services/nastool.png
  #       - homepage.href=https://nastool.${DOMAIN_SWARM}:4/
  #       - homepage.description=自动化管理多媒体资源       
  #       - homepage.ping=http://nastool:3000        
  #       - homepage.weight=5   
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.labels.type == vm
  #         - node.labels.media == true

  # NAS-Tools hsuyelin的open版本
  nastool:
    image: hsuyelin/nas-tools:latest
    networks: [network_cluster]
    restart: on-failure  
    extra_hosts:
      - "api.themoviedb.org:65.9.17.17"    
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      UMASK: ${MEDIA_UMASK}
      NASTOOL_AUTO_UPDATE: ${NASTOOL_AUTO_UPDATE}
      NASTOOL_CN_UPDATE: ${NASTOOL_CN_UPDATE}
      TZ: ${TZ}
    volumes:
      - nfs_nastool_media:/media
      - nfs_nastool_media_ext:/media_ext
      - nfs_nastool_config:/config
      - nfs_nastool_src:/nas-tools
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nastool.rule=Host(`nastool.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.nastool.entrypoints=websecure"
        - "traefik.http.routers.nastool.service=nastool"
        - "traefik.http.routers.nastool.middlewares=noauth-chain@file"
        - "traefik.http.services.nastool.loadbalancer.server.port=3000"      
        - homepage.group=Media
        - homepage.name=NASTool
        - homepage.icon=https://www.waylon.wang:4/images/services/nastool.png
        - homepage.href=https://nastool.${DOMAIN_SWARM}:4/
        - homepage.description=自动化管理多媒体资源       
        - homepage.siteMonitor=http://nastool:3000        
        - homepage.weight=5   
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true          

  # ChineseSubFinder
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    networks: [network_cluster]
    restart: on-failure   
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      UMASK: ${MEDIA_UMASK}
      PERMS: ${MEDIA_PERMS}  
      TZ: ${TZ}
    volumes:
      - nfs_chinesesubfinder_media:/media
      - nfs_chinesesubfinder_config:/config
    # ports:
    #   - 19037:19037
    # logging:
    #   driver: "json-file"
    #   options:
    #     ax-size: "100m" # 限制docker控制台日志大小，可自行调整      
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chinesesubfinder.rule=Host(`chinesesubfinder.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.chinesesubfinder.entrypoints=websecure"
        - "traefik.http.routers.chinesesubfinder.service=chinesesubfinder"
        - "traefik.http.routers.chinesesubfinder.middlewares=noauth-chain@file"
        - "traefik.http.services.chinesesubfinder.loadbalancer.server.port=19035"     
        - homepage.group=Media
        - homepage.name=ChineseSubFinder
        - homepage.icon=https://www.waylon.wang:4/images/services/chinesesubfinder.png
        - homepage.href=https://chinesesubfinder.${DOMAIN_SWARM}:4/
        - homepage.description=中文字幕检索   
        - homepage.ping=chinesesubfinder  
        - homepage.weight=40                
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true          

  # Jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    networks: [network_cluster]
    restart: on-failure   
    environment:
      # 直接使用Portainer容器内的环境变量
      PUID: ${MEDIA_PUID}
      PGID: ${MEDIA_PGID}
      UMASK: ${MEDIA_UMASK}
      TZ: ${TZ}
    volumes:
      - nfs_jackett_downloads:/downloads
      - nfs_jackett_config:/config  
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.jackett.entrypoints=websecure"
        - "traefik.http.routers.jackett.service=jackett"
        - "traefik.http.routers.jackett.middlewares=noauth-chain@file"
        - "traefik.http.services.jackett.loadbalancer.server.port=9117"   
        - homepage.group=Media
        - homepage.name=Jackett
        - homepage.icon=jackett.png
        - homepage.href=https://jackett.${DOMAIN_SWARM}:4/
        - homepage.description=种子检索    
        - homepage.ping=jackett
        - homepage.weight=20   
        # jackett widget必须无密码验证才有左右，配置无意义 
        # - homepage.widget.type=jackett
        # - homepage.widget.url=https://jackett.${DOMAIN_SWARM}:4    
        # - homepage.widget.key=${HOMEPAGE_JECKTEE_TOKEN}        
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true  

  # Jellyfin
  jellyfin:
    image: jellyfin/jellyfin
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    extra_hosts:
      - "api.themoviedb.org:65.9.17.17"
      - "api.thetvdb.com:13.35.45.141"
      - "image.tmdb.org:143.244.50.83"
      - "www.themoviedb.org:99.84.238.161"
    networks: [network_cluster]
    restart: on-failure    
    ports:
      - "44096:8096"
    volumes:
      - nfs_jellyfin_config:/config
      - nfs_jellyfin_cache:/cache
      - nfs_jellyfin_font:/usr/share/fonts/truetype/dejavu
      - nfs_jellyfin_lib1:/media_main_lib
      - nfs_jellyfin_lib2:/media_ext_lib
      #- ${VIDEO_MAIN_DIR}:/media
      - ${VIDEO_OTHER_DIR}:/other
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.middlewares=noauth-chain@file"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - homepage.group=Media
        - homepage.name=Jellyfin
        - homepage.icon=jellyfin.png
        - homepage.href=https://jellyfin.${DOMAIN_SWARM}:4/
        - homepage.description=影音播放服务
        - homepage.siteMonitor=http://jellyfin:8096     
        - homepage.weight=8   
        - homepage.widget.type=jellyfin
        - homepage.widget.url=https://jellyfin.${DOMAIN_SWARM}:4
        - homepage.widget.key=${HOMEPAGE_JELLYFIN_TOKEN}
        - homepage.widgetenableBlocks=true
        - homepage.widgetenableNowPlaying=true      
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == nas
          - node.labels.media == true
          - node.labels.nas == primary

networks:
  network_cluster:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

x-common-media-main-volume: &common-media-main-volume
  type: nfs
  o: addr=${MEDIA_SERVER},rw,nfsvers=4

x-common-media-ext-volume: &common-media-ext-volume
  type: nfs
  o: addr=${MEDIA_EXT_SERVER},rw,nfsvers=4

volumes:
  nfs_drpy:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/drpy/src
  nfs_drpy2:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/drpy2/src
  nfs_mylist:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/myalist/data
  nfs_jellyfin_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/config
  nfs_jellyfin_cache:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/cache
  nfs_jellyfin_font:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/font
  nfs_jellyfin_lib1:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}/links
  nfs_jellyfin_lib2:
    driver: local
    driver_opts:
      <<: *common-media-ext-volume
      device: :${MEDIA_DEVICE}/links
  nfs_nastool_media:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}   
  nfs_nastool_media_ext:
    driver: local
    driver_opts:
      <<: *common-media-ext-volume
      device: :${MEDIA_DEVICE}                
  nfs_nastool_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/nastool/config
  nfs_nastool_src:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/nastool/src      
  # nfs_open_nastool_media:
  #   driver: local
  #   driver_opts:
  #     <<: *common-media-main-volume
  #     device: :${MEDIA_DEVICE}   
  # nfs_open_nastool_media_ext:
  #   driver: local
  #   driver_opts:
  #     <<: *common-media-ext-volume
  #     device: :${MEDIA_DEVICE}                
  # nfs_open_nastool_config:
  #   driver: local
  #   driver_opts:
  #     <<: *common-keys-volume
  #     device: :${NFS_DEVICE}/media/open-nastool/config
  # nfs_open_nastool_src:
  #   driver: local
  #   driver_opts:
  #     <<: *common-keys-volume
  #     device: :${NFS_DEVICE}/media/open-nastool/src  
  nfs_chinesesubfinder_media:
    driver: local
    driver_opts:
      <<: *common-media-main-volume
      device: :${MEDIA_DEVICE}          
  nfs_chinesesubfinder_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/chinesesubfinder/config      
  nfs_jackett_downloads:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jackett/downloads          
  nfs_jackett_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jackett/config          