version: "3.4"

services:
  # Drpy
  drpy:
    image: esme518/docker-drpy
    networks: [network_cluster]
    restart: on-failure
    environment:
      user: root
      # INET_USERNAME: ${DRPY_USERNAME}
      # INET_PASSWORD: ${DRPY_PASSWORD}
      TZ: ${TZ}       
    volumes:
      - nfs_drpy:/root/sd/pywork/dr_py
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drpy1.rule=Host(`drpy.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpy1.entrypoints=websecure"
        - "traefik.http.routers.drpy1.service=drpy1"
        - "traefik.http.routers.drpy1.middlewares=noauth-chain@file"
        - "traefik.http.services.drpy1.loadbalancer.server.port=9001"
        - "traefik.http.routers.drpy2.rule=Host(`drpy.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.drpy2.entrypoints=websecure"
        - "traefik.http.routers.drpy2.service=drpy2"
        - "traefik.http.routers.drpy2.middlewares=noauth-chain@file"
        - "traefik.http.services.drpy2.loadbalancer.server.port=5705"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true

  # MyAlist
  myalist:
    image: xhofe/alist:latest
    networks: [network_cluster]
    restart: on-failure
    environment:
      PUID: ${MYALIST_PUID}
      PGID: ${MYALIST_PGID}
      UMASK: ${MYALIST_UMASK}
      TZ: ${TZ}       
    volumes:
      - nfs_mylist:/opt/alist/data
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myalist.rule=Host(`myalist.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.myalist.entrypoints=websecure"
        - "traefik.http.routers.myalist.middlewares=noauth-chain@file"
        - "traefik.http.services.myalist.loadbalancer.server.port=5244"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == vm
          - node.labels.media == true

  # Jellyfin
  jellyfin:
    image: jellyfin/jellyfin
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    extra_hosts:
      - "api.themoviedb.org:13.225.170.110"
      - "api.thetvdb.com:13.35.45.141"
      - "image.tmdb.org:99.84.238.101"
      - "www.themoviedb.org:99.84.203.104"
    networks: [network_cluster]
    restart: on-failure    
    ports:
      - "44096:8096"
    volumes:
      - nfs_jellyfin_config:/config
      - nfs_jellyfin_cache:/cache
      - nfs_jellyfin_font:/usr/share/fonts/truetype/dejavu
      - nfs_jellyfin_lib:/medialib
      - ${VIDEO_MAIN_DIR}:/media
      - ${VIDEO_OTHER_DIR}:/other
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_SWARM}`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.middlewares=noauth-chain@file"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == nas
          - node.labels.nas == primary

networks:
  network_cluster:
    external: true

x-common-keys-volume: &common-keys-volume
  type: nfs
  o: addr=${NFS_SERVER},rw,nfsvers=4

volumes:
  nfs_drpy:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/drpy/src
  nfs_mylist:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/myalist/data
  nfs_jellyfin_config:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/config
  nfs_jellyfin_cache:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/cache
  nfs_jellyfin_font:
    driver: local
    driver_opts:
      <<: *common-keys-volume
      device: :${NFS_DEVICE}/media/jellyfin/font
  nfs_jellyfin_lib:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.11.82,rw,nfsvers=4
      device: :/multimedia
